set up directories
  $ DATDIR=$TESTDIR/data
  $ BIN=$TESTDIR/../pbihdfutils/bin/
  $ EXEC=$BIN/toAfg

test basic FASTA use case
  $ $EXEC $DATDIR/read.fasta output.afg -noSplitSubreads
  $ head output.afg
  {UNV
  iid:1
  com:
  generated by AfgBasWriter
  Mon Jun 28 14:43:52 2010
  .
  }
  {LIB
  iid:1
  {DST
  $ tail output.afg
  qlt:
  55555555555555555555555555555555555555555555555555555555555555555555555555555555
  55555555555555555555
  .
  }
  {FRG
  iid:24
  lib:1
  typ:I
  }

test uniform QV use case
  $ $EXEC $DATDIR/tiny.fastq output.afg -noSplitSubreads -uniformQV 3
  $ head output.afg
  {UNV
  iid:1
  com:
  generated by AfgBasWriter
  Mon Jun 28 14:43:52 2010
  .
  }
  {LIB
  iid:1
  {DST
  $ tail output.afg
  33333333333333333333333333333333333333333333333333333333333333333333333333333333
  33333333333333333333333333333333333333333333333333333333333333333333333333333333
  3333333333333333333333333333333333333333333333333333333333333
  .
  }
  {FRG
  iid:4
  lib:1
  typ:I
  }

test uniform QV FASTA use case
  $ $EXEC $DATDIR/read.fasta output.afg -noSplitSubreads -uniformQV 7
  $ head output.afg
  {UNV
  iid:1
  com:
  generated by AfgBasWriter
  Mon Jun 28 14:43:52 2010
  .
  }
  {LIB
  iid:1
  {DST
  $ tail output.afg
  qlt:
  77777777777777777777777777777777777777777777777777777777777777777777777777777777
  77777777777777777777
  .
  }
  {FRG
  iid:24
  lib:1
  typ:I
  }

